# Generated by Django 5.1.3 on 2025-03-12 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0004_alter_producto_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='productos.producto')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
