# Generated by Django 5.1.3 on 2024-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'categoria_producto',
                'verbose_name_plural': 'categoria_producto',
                'db_table': 'categoria_producto',
                'managed': True,
            },
        ),
    ]
