# Generated by Django 5.1.3 on 2025-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria_producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
