# Generated by Django 5.1.3 on 2024-12-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.IntegerField(blank=True, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=45, null=True)),
                ('detalle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'catalogo',
                'verbose_name_plural': 'catalogo',
                'db_table': 'catalogo',
                'managed': True,
            },
        ),
    ]
