# Generated by Django 5.1.3 on 2025-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'managed': True, 'verbose_name': 'catalogo', 'verbose_name_plural': 'catalogos'},
        ),
        migrations.AddField(
            model_name='catalogo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
