# Generated by Django 5.1.3 on 2025-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
