# Generated by Django 5.1.3 on 2026-05-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_catalogo_options_catalogo_color_and_more'),
        ('catalogos', '0002_catalogo_color'),
    ]

    operations = [
    ]
