# Generated by Django 5.1.3 on 2024-12-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria_producto', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('categoria_producto_id', models.ForeignKey(blank=True, db_column='categoria_producto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='categoria_producto.categoriaproducto')),
            ],
            options={
                'verbose_name': 'paquetes',
                'verbose_name_plural': 'paquetes',
                'db_table': 'paquetes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaqueteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(blank=True, max_length=45, null=True)),
                ('duracion_horas', models.CharField(blank=True, max_length=45, null=True)),
                ('costo_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paquete', models.ForeignKey(db_column='paquetes_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='paquetes.paquete')),
                ('producto', models.ForeignKey(db_column='productos_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_paquete', to='productos.producto')),
            ],
            options={
                'verbose_name': 'paquete_detalle',
                'verbose_name_plural': 'paquete_detalle',
                'db_table': 'paquete_detalle',
                'managed': True,
            },
        ),
    ]
