# Generated by Django 5.1.3 on 2024-12-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria_producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
                ('tipo_costo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('categoria_producto_id', models.ForeignKey(blank=True, db_column='categoria_producto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='categoria_producto.categoriaproducto')),
            ],
            options={
                'verbose_name': 'productos',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'managed': True,
            },
        ),
    ]
