# Generated by Django 5.1.3 on 2025-02-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_deleted_at'),
        ('cotizaciones', '0001_initial'),
        ('paquetes', '0001_initial'),
        ('productos', '0002_producto_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'managed': True, 'verbose_name': 'cotizaciones', 'verbose_name_plural': 'cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizaciondetalle',
            options={'managed': True, 'verbose_name': 'cotizacion_detalle', 'verbose_name_plural': 'cotizacion_detalle'},
        ),
        migrations.RemoveField(
            model_name='cotizaciondetalle',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(db_column='clientes_id', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='cotizacion',
            field=models.ForeignKey(db_column='cotizaciones_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cotizaciones.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='paquete',
            field=models.ForeignKey(blank=True, db_column='paquetes_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='paquetes.paquete'),
        ),
        migrations.AlterModelTable(
            name='cotizacion',
            table='cotizaciones',
        ),
        migrations.AlterModelTable(
            name='cotizaciondetalle',
            table='cotizacion_detalle',
        ),
    ]
