# Generated by Django 5.1.3 on 2025-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='duracion_evento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_evento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vigencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_evento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_evento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
