# Generated by Django 5.2.13 on 2026-06-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_remove_empresa_subdominio_empresa_max_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioempresa',
            name='es_admin_empresa',
            field=models.BooleanField(default=False),
        ),
    ]
